[project]
name = "save_url"
version = "1.1.0"
description = "Script to save and url in a single file with an automatic and structured name. It uses monolith as its backend"
authors = [
    {name = "turulomio",email = "turulomio@yahoo.es"}
]
license = {text = "GPL-3.0-only"}
readme = "README.md"
requires-python = ">=3.14,<4.0.0"
dependencies = [
    "mechanize >=0.4.10",
    "colorama >=0.4.6",
    "pydicts >=1.5.0",
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
poetry = ">=2.5.1"
poethepoet = ">=0.48.0"
pytest = ">=8.0.0"
pytest-cov = ">=5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
homepage = "https://github.com/turulomio/save_url/"
repository = "https://github.com/turulomio/save_url/"
changelog = "https://github.com/turulomio/save_url#changelog"

[tool.poetry.scripts]
save_url = 'save_url.core:console_save_url'
save_url_singlefile = 'save_url.core:console_save_url_singlefile'
save_url_monolith = 'save_url.core:console_save_url_monolith'

[tool.poe.tasks]
release = { script = "save_url.poethepoet:release" }
translate = { script = "save_url.poethepoet:translate" }
monolith_ebuild = { script = "save_url.poethepoet:monolith_ebuild" }
pytest = { script = "save_url.poethepoet:pytest" }
test = { script = "save_url.poethepoet:pytest" }